import { NextRequest, NextResponse } from "next/server";
import { db } from "@rankflo/db";

/**
 * llms.txt — AI Discoverability Endpoint
 *
 * Returns a structured text file following the llms.txt specification
 * so AI assistants (ChatGPT, Perplexity, Claude) can discover and
 * cite your published content.
 *
 * GET /api/v1/llms.txt?project_key=rf_xxx
 *
 * Usage in your Next.js app:
 *   // app/llms.txt/route.ts
 *   export async function GET() {
 *     const res = await fetch(`${RANKFLO_URL}/api/v1/llms.txt?project_key=${API_KEY}`)
 *     return new Response(await res.text(), { headers: { 'Content-Type': 'text/plain' } })
 *   }
 */
export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const authHeader = req.headers.get("authorization");
  const apiKey = authHeader?.startsWith("Bearer ")
    ? authHeader.slice(7)
    : url.searchParams.get("project_key");

  if (!apiKey) {
    return new NextResponse("Missing API key", { status: 401 });
  }

  const project = await db.project.findUnique({
    where: { apiKey },
    select: { id: true, organizationId: true, name: true, url: true, description: true, status: true },
  });

  if (!project) {
    return new NextResponse("Invalid API key", { status: 401 });
  }

  if (project.status === "ARCHIVED") {
    return new NextResponse("Project archived", { status: 403 });
  }

  const posts = await db.post.findMany({
    where: {
      projectId: project.id,
      organizationId: project.organizationId,
      status: "PUBLISHED",
      deletedAt: null,
    },
    orderBy: { publishedAt: "desc" },
    take: 100,
    select: {
      title: true,
      slug: true,
      excerpt: true,
      publishedAt: true,
      contentPlain: true,
      seoMeta: { select: { metaDescription: true } },
      tags: { include: { tag: { select: { name: true } } } },
    },
  });

  const siteUrl = project.url?.replace(/\/$/, "") ?? "";

  const lines: string[] = [
    `# ${project.name}`,
    ``,
    `> ${project.description ?? `${project.name} — content published via RankFlo`}`,
    ``,
    `Source: ${siteUrl}`,
    ``,
    `## Blog Posts`,
    ``,
  ];

  for (const post of posts) {
    const desc = post.seoMeta?.metaDescription ?? post.excerpt ?? "";
    const tags = post.tags.map(t => t.tag.name).join(", ");
    const postUrl = siteUrl ? `${siteUrl}/blog/${post.slug}` : `/blog/${post.slug}`;

    lines.push(`### ${post.title}`);
    lines.push(``);
    if (desc) lines.push(`${desc}`);
    lines.push(``);
    lines.push(`URL: ${postUrl}`);
    if (post.publishedAt) {
      lines.push(`Published: ${new Date(post.publishedAt).toISOString().split("T")[0]}`);
    }
    if (tags) lines.push(`Tags: ${tags}`);
    lines.push(``);
  }

  if (posts.length === 0) {
    lines.push(`No published content yet.`);
  }

  lines.push(`---`);
  lines.push(`Generated by RankFlo — https://rankflo.io`);

  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
      "Access-Control-Allow-Origin": "*",
    },
  });
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET" },
  });
}
