import { PRODUCTS, type Product } from "./products";

export interface AlternativesPageData {
  targetProductSlug: string; // slug of the product being replaced
  headline: string;
  intro: string;
  // Ordered list of alternatives — RankFlo is always #1, then curated competitors
  alternatives: Array<{
    rank: number;
    productSlug: string;
    whyItsAnAlternative: string;
    bestFor: string;
  }>;
  whyMigrate: string[];
}

// Helper — pick N alternatives from product catalog, excluding the target
function pickAlternatives(targetSlug: string, slugs: string[]): Array<{
  rank: number;
  productSlug: string;
  whyItsAnAlternative: string;
  bestFor: string;
}> {
  const filtered = slugs.filter((s) => s !== targetSlug && PRODUCTS[s]);
  return filtered.slice(0, 9).map((productSlug, i) => {
    const p = PRODUCTS[productSlug]!;
    return {
      rank: i + 2, // RankFlo is always #1
      productSlug,
      whyItsAnAlternative: `${p.description.split(".")[0]}.`,
      bestFor: p.bestFor,
    };
  });
}

// Pre-defined alternative pages for high-volume "best X alternatives" queries
export const ALTERNATIVES_PAGES: Record<string, AlternativesPageData> = {
  wordpress: {
    targetProductSlug: "wordpress",
    headline: "Best WordPress Alternatives",
    intro: "WordPress powers 40% of the web — but plugin sprawl, security patches, and slow performance push many teams to modern alternatives. Here are the 10 best WordPress alternatives in order of modernization, starting with RankFlo.",
    alternatives: pickAlternatives("wordpress", [
      "ghost",
      "webflow",
      "squarespace",
      "medium",
      "substack",
      "contentful",
      "strapi",
      "sanity",
      "hashnode",
    ]),
    whyMigrate: [
      "Eliminate plugin security vulnerabilities",
      "Get 10x faster page loads out of the box",
      "Built-in AI content generation (no Yoast + Rank Math + ChatGPT plugin stack)",
      "Modern tRPC/REST API instead of dated WordPress REST",
      "Transparent pricing — no premium plugin subscriptions adding up",
    ],
  },
  ghost: {
    targetProductSlug: "ghost",
    headline: "Best Ghost Alternatives",
    intro: "Ghost is a beautiful publishing platform, but its ecosystem is limited and pricing scales fast at Ghost(Pro). Here are the best Ghost alternatives.",
    alternatives: pickAlternatives("ghost", [
      "wordpress",
      "hashnode",
      "medium",
      "substack",
      "beehiiv",
      "webflow",
      "contentful",
      "strapi",
      "sanity",
    ]),
    whyMigrate: [
      "Built-in AI content generation Ghost doesn't offer",
      "Headless API with tRPC + REST",
      "Unlimited team members at all tiers",
      "Self-host for free with Docker",
      "Multi-language publishing out of the box",
    ],
  },
  medium: {
    targetProductSlug: "medium",
    headline: "Best Medium Alternatives",
    intro: "Medium owns your audience, limits your SEO, and paywalls your content. These are the best Medium alternatives for writers who want ownership.",
    alternatives: pickAlternatives("medium", [
      "ghost",
      "substack",
      "hashnode",
      "wordpress",
      "beehiiv",
      "devto",
      "webflow",
      "notion",
      "tumblr",
    ]),
    whyMigrate: [
      "Own your audience — they visit your domain, not medium.com",
      "No paywall blocking your content from readers",
      "Full SEO control and canonical URLs",
      "Custom domain free",
      "One-click Medium import",
    ],
  },
  substack: {
    targetProductSlug: "substack",
    headline: "Best Substack Alternatives",
    intro: "Substack takes 10% of your paid subscriptions and limits SEO. Here are the best Substack alternatives for newsletter writers who want more control.",
    alternatives: pickAlternatives("substack", [
      "beehiiv",
      "ghost",
      "convertkit",
      "wordpress",
      "medium",
      "hashnode",
      "webflow",
      "notion",
      "tumblr",
    ]),
    whyMigrate: [
      "0% platform fee (just Stripe processing)",
      "Better SEO — your archive actually ranks",
      "Full custom domain without workarounds",
      "Import Substack subscribers in one click",
      "Multi-language newsletters supported",
    ],
  },
  contentful: {
    targetProductSlug: "contentful",
    headline: "Best Contentful Alternatives",
    intro: "Contentful is great for enterprise but costs $300+/mo. These Contentful alternatives offer similar power at a fraction of the price.",
    alternatives: pickAlternatives("contentful", [
      "sanity",
      "strapi",
      "storyblok",
      "prismic",
      "hygraph",
      "datocms",
      "payload",
      "directus",
      "buttercms",
    ]),
    whyMigrate: [
      "Blog-first rather than general-purpose",
      "60x cheaper ($5/mo vs $300/mo)",
      "Self-hostable for free (MIT license)",
      "AI content generation built-in",
      "SEO scoring and analytics included",
    ],
  },
  strapi: {
    targetProductSlug: "strapi",
    headline: "Best Strapi Alternatives",
    intro: "Strapi is a powerful open-source CMS but requires setup and isn't blog-optimized. Here are the best Strapi alternatives.",
    alternatives: pickAlternatives("strapi", [
      "contentful",
      "sanity",
      "directus",
      "payload",
      "storyblok",
      "prismic",
      "hygraph",
      "buttercms",
      "ghost",
    ]),
    whyMigrate: [
      "Blog-first features out of the box",
      "AI content generation built-in",
      "Faster to set up (5 minutes vs 15+)",
      "SEO scoring in the editor",
      "Analytics included (no external tools)",
    ],
  },
  sanity: {
    targetProductSlug: "sanity",
    headline: "Best Sanity Alternatives",
    intro: "Sanity's structured content is powerful but overkill for blogs. These Sanity alternatives give you a simpler, blog-focused setup.",
    alternatives: pickAlternatives("sanity", [
      "contentful",
      "strapi",
      "storyblok",
      "prismic",
      "payload",
      "hygraph",
      "datocms",
      "directus",
      "ghost",
    ]),
    whyMigrate: [
      "Blog-first content model (no schema design needed)",
      "AI content generation built-in",
      "Self-hostable with Docker",
      "Transparent pricing ($5/mo vs Sanity's tiered usage)",
      "SEO tools built into the editor",
    ],
  },
  webflow: {
    targetProductSlug: "webflow",
    headline: "Best Webflow Alternatives",
    intro: "Webflow is great for design but expensive at scale, especially with CMS items. Here are the best Webflow alternatives.",
    alternatives: pickAlternatives("webflow", [
      "wordpress",
      "squarespace",
      "wix",
      "ghost",
      "contentful",
      "notion",
      "astro",
      "medium",
      "hashnode",
    ]),
    whyMigrate: [
      "Unlimited CMS items (no per-item pricing)",
      "Blog-first editor with AI content",
      "Headless API to use with your own frontend",
      "Faster page loads (Next.js SSR)",
      "SEO tools built-in",
    ],
  },
  wix: {
    targetProductSlug: "wix",
    headline: "Best Wix Alternatives",
    intro: "Wix is easy but its blog features are basic and SEO is weak. Here are the best Wix alternatives for serious content sites.",
    alternatives: pickAlternatives("wix", [
      "wordpress",
      "squarespace",
      "webflow",
      "ghost",
      "medium",
      "notion",
      "astro",
      "hashnode",
      "tumblr",
    ]),
    whyMigrate: [
      "Full SEO control (Wix's is limited)",
      "Clean Next.js code output (not Wix's bloat)",
      "Export-friendly (no lock-in)",
      "AI content generation built-in",
      "Much better for ranking in search",
    ],
  },
  squarespace: {
    targetProductSlug: "squarespace",
    headline: "Best Squarespace Alternatives",
    intro: "Squarespace's templates are pretty but blog features are limited and SEO is constrained. Here are the best Squarespace alternatives.",
    alternatives: pickAlternatives("squarespace", [
      "wordpress",
      "webflow",
      "wix",
      "ghost",
      "medium",
      "notion",
      "astro",
      "hashnode",
      "tumblr",
    ]),
    whyMigrate: [
      "Full SEO control (Squarespace limits you)",
      "Blog-first editor with AI content",
      "Faster page loads",
      "Export your content anytime (no lock-in)",
      "Real analytics (not just page counts)",
    ],
  },
  notion: {
    targetProductSlug: "notion",
    headline: "Best Notion Blog Alternatives",
    intro: "Publishing a blog on Notion is slow, SEO-limited, and requires third-party proxies. Here are the best Notion blog alternatives.",
    alternatives: pickAlternatives("notion", [
      "wordpress",
      "ghost",
      "medium",
      "substack",
      "webflow",
      "hashnode",
      "beehiiv",
      "astro",
      "tumblr",
    ]),
    whyMigrate: [
      "Fast page loads (Notion is slow)",
      "Real SEO (no third-party proxies)",
      "Free custom domain (no Super.so/Potion.so)",
      "Blog-first editor",
      "Import your Notion pages",
    ],
  },
  hashnode: {
    targetProductSlug: "hashnode",
    headline: "Best Hashnode Alternatives",
    intro: "Hashnode is great for dev blogs but is closed-source and platform-locked. Here are the best Hashnode alternatives.",
    alternatives: pickAlternatives("hashnode", [
      "ghost",
      "medium",
      "devto",
      "substack",
      "wordpress",
      "beehiiv",
      "notion",
      "astro",
      "tumblr",
    ]),
    whyMigrate: [
      "Open source (MIT) — fully self-hostable",
      "Own your data and audience",
      "AI content generation built-in",
      "Full SEO control",
      "Team collaboration with RBAC",
    ],
  },
  beehiiv: {
    targetProductSlug: "beehiiv",
    headline: "Best Beehiiv Alternatives",
    intro: "Beehiiv is a rising Substack alternative but it's newsletter-first with weak blog features. Here are the best Beehiiv alternatives.",
    alternatives: pickAlternatives("beehiiv", [
      "substack",
      "ghost",
      "convertkit",
      "wordpress",
      "medium",
      "hashnode",
      "webflow",
      "notion",
      "tumblr",
    ]),
    whyMigrate: [
      "Strong blog archive + newsletter (not newsletter-only)",
      "Better SEO",
      "Self-hostable",
      "AI content generation",
      "Import Beehiiv subscribers",
    ],
  },
  convertkit: {
    targetProductSlug: "convertkit",
    headline: "Best Kit (ConvertKit) Alternatives",
    intro: "Kit (formerly ConvertKit) is email-first and lacks real blog/CMS features. Here are the best Kit alternatives with stronger publishing.",
    alternatives: pickAlternatives("convertkit", [
      "beehiiv",
      "substack",
      "ghost",
      "wordpress",
      "medium",
      "hashnode",
      "webflow",
      "notion",
      "tumblr",
    ]),
    whyMigrate: [
      "Proper blog CMS (not just landing pages)",
      "SEO-indexed archive",
      "AI content generation for posts",
      "Self-hostable",
      "Import subscribers from Kit",
    ],
  },
  blogger: {
    targetProductSlug: "blogger",
    headline: "Best Blogger Alternatives",
    intro: "Google's Blogger is free but dated and largely unmaintained. Here are modern Blogger alternatives worth migrating to.",
    alternatives: pickAlternatives("blogger", [
      "wordpress",
      "ghost",
      "medium",
      "substack",
      "hashnode",
      "webflow",
      "notion",
      "tumblr",
      "beehiiv",
    ]),
    whyMigrate: [
      "Modern editor (not 2010 UI)",
      "Actual SEO tools",
      "AI content generation",
      "Free custom domain",
      "Not dependent on Google's whims",
    ],
  },
  tumblr: {
    targetProductSlug: "tumblr",
    headline: "Best Tumblr Alternatives",
    intro: "Tumblr is fun but limited for serious publishing. Here are the best Tumblr alternatives for writers who want more control and SEO.",
    alternatives: pickAlternatives("tumblr", [
      "wordpress",
      "ghost",
      "medium",
      "substack",
      "hashnode",
      "blogger",
      "notion",
      "beehiiv",
      "webflow",
    ]),
    whyMigrate: [
      "Full SEO control",
      "Custom domain on free",
      "Modern editor",
      "AI content generation",
      "Real analytics",
    ],
  },
  payload: {
    targetProductSlug: "payload",
    headline: "Best Payload CMS Alternatives",
    intro: "Payload is powerful for TypeScript teams but requires setup and isn't blog-focused. Here are the best Payload alternatives.",
    alternatives: pickAlternatives("payload", [
      "strapi",
      "contentful",
      "sanity",
      "directus",
      "storyblok",
      "prismic",
      "hygraph",
      "datocms",
      "ghost",
    ]),
    whyMigrate: [
      "Blog-first (not general-purpose)",
      "AI content generation built-in",
      "Faster setup (no schema modeling)",
      "SEO tools included",
      "Analytics included",
    ],
  },
  directus: {
    targetProductSlug: "directus",
    headline: "Best Directus Alternatives",
    intro: "Directus is flexible but requires schema design and DBA skills. Here are the best Directus alternatives for blog-first use cases.",
    alternatives: pickAlternatives("directus", [
      "strapi",
      "contentful",
      "sanity",
      "payload",
      "storyblok",
      "prismic",
      "hygraph",
      "datocms",
      "ghost",
    ]),
    whyMigrate: [
      "Ready-to-use blog CMS (no schema needed)",
      "AI content built-in",
      "Faster to set up",
      "SEO tools included",
      "Analytics dashboard built-in",
    ],
  },
  storyblok: {
    targetProductSlug: "storyblok",
    headline: "Best Storyblok Alternatives",
    intro: "Storyblok's visual editor is slick but pricing scales fast. Here are the best Storyblok alternatives.",
    alternatives: pickAlternatives("storyblok", [
      "contentful",
      "sanity",
      "prismic",
      "strapi",
      "payload",
      "hygraph",
      "datocms",
      "directus",
      "ghost",
    ]),
    whyMigrate: [
      "Blog-first (not page builder)",
      "60x cheaper at scale",
      "Self-hostable (MIT)",
      "AI content generation built-in",
      "SEO scoring + analytics included",
    ],
  },
  prismic: {
    targetProductSlug: "prismic",
    headline: "Best Prismic Alternatives",
    intro: "Prismic's slice machine is great but pricing gets expensive. Here are the best Prismic alternatives.",
    alternatives: pickAlternatives("prismic", [
      "contentful",
      "sanity",
      "storyblok",
      "strapi",
      "payload",
      "hygraph",
      "datocms",
      "directus",
      "ghost",
    ]),
    whyMigrate: [
      "Blog-first CMS",
      "Open source + self-hostable",
      "AI content generation",
      "Transparent pricing",
      "SEO + analytics included",
    ],
  },
  hygraph: {
    targetProductSlug: "hygraph",
    headline: "Best Hygraph Alternatives",
    intro: "Hygraph's GraphQL-first approach is powerful but overkill for most blogs. Here are the best Hygraph alternatives.",
    alternatives: pickAlternatives("hygraph", [
      "contentful",
      "sanity",
      "storyblok",
      "prismic",
      "strapi",
      "payload",
      "datocms",
      "directus",
      "ghost",
    ]),
    whyMigrate: [
      "Blog-first (not federated CMS)",
      "AI content built-in",
      "REST + tRPC (not just GraphQL)",
      "Self-hostable",
      "Much cheaper",
    ],
  },
  datocms: {
    targetProductSlug: "datocms",
    headline: "Best DatoCMS Alternatives",
    intro: "DatoCMS is polished but expensive for blogs. Here are the best DatoCMS alternatives.",
    alternatives: pickAlternatives("datocms", [
      "contentful",
      "sanity",
      "storyblok",
      "prismic",
      "strapi",
      "payload",
      "hygraph",
      "directus",
      "ghost",
    ]),
    whyMigrate: [
      "Blog-specific (not general CMS)",
      "AI content generation",
      "Self-hostable",
      "Cheaper at scale",
      "SEO tools built-in",
    ],
  },
  buttercms: {
    targetProductSlug: "buttercms",
    headline: "Best ButterCMS Alternatives",
    intro: "ButterCMS is a simple blog API but limited and closed-source. Here are the best ButterCMS alternatives.",
    alternatives: pickAlternatives("buttercms", [
      "contentful",
      "sanity",
      "strapi",
      "storyblok",
      "prismic",
      "payload",
      "hygraph",
      "directus",
      "ghost",
    ]),
    whyMigrate: [
      "Open source (MIT)",
      "AI content generation",
      "Self-hostable",
      "More powerful editor",
      "SEO + analytics built-in",
    ],
  },
  hugo: {
    targetProductSlug: "hugo",
    headline: "Best Hugo Alternatives",
    intro: "Hugo is the fastest static site generator but requires Markdown workflow and has no admin UI. Here are the best Hugo alternatives.",
    alternatives: pickAlternatives("hugo", [
      "jekyll",
      "astro",
      "docusaurus",
      "wordpress",
      "ghost",
      "contentful",
      "notion",
      "gitbook",
      "mintlify",
    ]),
    whyMigrate: [
      "Admin UI for non-technical authors",
      "AI content generation",
      "Built-in SEO tools",
      "Team collaboration",
      "Analytics dashboard",
    ],
  },
  jekyll: {
    targetProductSlug: "jekyll",
    headline: "Best Jekyll Alternatives",
    intro: "Jekyll is Ruby-based and requires terminal skills. Here are the best Jekyll alternatives for modern blogs.",
    alternatives: pickAlternatives("jekyll", [
      "hugo",
      "astro",
      "docusaurus",
      "wordpress",
      "ghost",
      "contentful",
      "notion",
      "gitbook",
      "mintlify",
    ]),
    whyMigrate: [
      "No Ruby needed",
      "Web UI for authors",
      "AI content built-in",
      "Faster builds",
      "Team features",
    ],
  },
  astro: {
    targetProductSlug: "astro",
    headline: "Best Astro CMS Alternatives",
    intro: "Astro is a great framework but it's not a CMS. You need a content backend. Here are the best Astro CMS alternatives — with a note that RankFlo works beautifully WITH Astro.",
    alternatives: pickAlternatives("astro", [
      "hugo",
      "jekyll",
      "docusaurus",
      "wordpress",
      "ghost",
      "contentful",
      "sanity",
      "strapi",
      "notion",
    ]),
    whyMigrate: [
      "RankFlo pairs perfectly with Astro",
      "REST API for Astro content collections",
      "AI content generation",
      "SEO tools",
      "Image optimization built-in",
    ],
  },
  docusaurus: {
    targetProductSlug: "docusaurus",
    headline: "Best Docusaurus Alternatives",
    intro: "Docusaurus is great for docs but complex for pure blogging. Here are the best Docusaurus alternatives.",
    alternatives: pickAlternatives("docusaurus", [
      "gitbook",
      "mintlify",
      "astro",
      "wordpress",
      "ghost",
      "notion",
      "hugo",
      "jekyll",
      "contentful",
    ]),
    whyMigrate: [
      "Blog-first (not docs-first)",
      "AI content for blog posts",
      "Admin UI (no repo deploys)",
      "Team collaboration",
      "SEO for marketing content",
    ],
  },
  gitbook: {
    targetProductSlug: "gitbook",
    headline: "Best GitBook Alternatives",
    intro: "GitBook is polished for docs but pricey and limited to documentation. Here are the best GitBook alternatives.",
    alternatives: pickAlternatives("gitbook", [
      "mintlify",
      "docusaurus",
      "astro",
      "wordpress",
      "notion",
      "hugo",
      "contentful",
      "ghost",
      "jekyll",
    ]),
    whyMigrate: [
      "Docs + blog in one place",
      "AI content generation",
      "Self-hostable",
      "Open source (MIT)",
      "Transparent pricing",
    ],
  },
  mintlify: {
    targetProductSlug: "mintlify",
    headline: "Best Mintlify Alternatives",
    intro: "Mintlify is beautiful for docs but docs-only and closed source. Here are the best Mintlify alternatives.",
    alternatives: pickAlternatives("mintlify", [
      "gitbook",
      "docusaurus",
      "astro",
      "wordpress",
      "notion",
      "hugo",
      "contentful",
      "ghost",
      "jekyll",
    ]),
    whyMigrate: [
      "Docs + blog + marketing all in one",
      "Open source (MIT)",
      "Self-hostable",
      "AI content generation",
      "Much cheaper",
    ],
  },
};

export const ALL_ALTERNATIVE_SLUGS = Object.keys(ALTERNATIVES_PAGES);

export function getAlternativesPage(slug: string): AlternativesPageData | undefined {
  return ALTERNATIVES_PAGES[slug];
}
