export interface GlossaryTerm {
  slug: string;
  term: string;
  shortDef: string;
  definition: string;
  example?: string;
  relatedTerms?: string[];
  category: "seo" | "content" | "cms" | "analytics" | "ai" | "technical" | "marketing";
}

const T = (t: Omit<GlossaryTerm, "slug">): [string, GlossaryTerm] => {
  const slug = t.term.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return [slug, { slug, ...t }];
};

export const GLOSSARY: Record<string, GlossaryTerm> = Object.fromEntries([
  // === SEO FUNDAMENTALS ===
  T({ term: "SEO", shortDef: "Search engine optimization.", definition: "Search Engine Optimization (SEO) is the practice of improving a website so it ranks higher in search engine results pages (SERPs). It encompasses technical SEO (site speed, crawlability), on-page SEO (content, keywords, metadata), and off-page SEO (backlinks, authority).", example: "A SaaS company publishing blog posts targeting \"best [category] software\" queries is doing SEO.", category: "seo", relatedTerms: ["serp", "keyword", "backlink"] }),
  T({ term: "SERP", shortDef: "Search engine results page.", definition: "A SERP is the page Google (or Bing) shows after a user types a query. Modern SERPs include organic results, ads, featured snippets, People Also Ask boxes, knowledge panels, image carousels, and increasingly AI overviews.", example: "When someone searches \"best headless CMS\", the SERP has 10 organic results, a comparison table, and often an AI overview.", category: "seo" }),
  T({ term: "Keyword", shortDef: "A search query target.", definition: "A keyword is a word or phrase users type into search engines. SEO content is optimized around target keywords (e.g., \"blog title generator\"). Modern SEO emphasizes search intent and topic clusters over single keywords.", category: "seo" }),
  T({ term: "Long-tail keyword", shortDef: "Specific, low-volume search queries.", definition: "Long-tail keywords are longer, more specific queries with lower search volume but higher intent. They're easier to rank for and convert better. Example: \"best headless CMS for Next.js 15\" (long-tail) vs \"CMS\" (head).", category: "seo" }),
  T({ term: "Search intent", shortDef: "What the user is trying to do.", definition: "Search intent is the goal behind a query: informational (learn something), navigational (find a site), commercial (compare options), or transactional (buy now). Google ranks pages that best match intent.", category: "seo" }),
  T({ term: "Featured snippet", shortDef: "Answer box at top of Google.", definition: "A featured snippet is the answer box Google shows above organic results for some queries. It pulls content directly from a page. Ranking in a featured snippet can double your CTR.", category: "seo" }),
  T({ term: "Meta description", shortDef: "Page summary shown in search results.", definition: "A meta description is an HTML tag (around 155 chars) summarizing a page. It appears under the title in SERPs. Not a ranking factor directly, but affects click-through rate.", category: "seo", relatedTerms: ["meta-title", "ctr"] }),
  T({ term: "Meta title", shortDef: "Page title shown in SERPs.", definition: "The meta title (<title> tag) is what shows as the clickable headline in search results. Google may rewrite it. Keep it under 60 chars, include primary keyword near the start.", category: "seo" }),
  T({ term: "Title tag", shortDef: "HTML element for the page title.", definition: "The <title> tag in HTML is one of the strongest on-page SEO signals. It tells search engines and browsers what the page is about.", category: "seo" }),
  T({ term: "H1", shortDef: "The main page heading.", definition: "An <h1> is the main heading of a page. Best practice: exactly one H1 per page that describes the main topic. It's the strongest on-page heading signal for SEO.", category: "seo" }),
  T({ term: "Canonical URL", shortDef: "The preferred URL for a page.", definition: "A canonical URL tells search engines which version of a page is the \"original\" when multiple URLs have similar content. Use <link rel=\"canonical\"> to prevent duplicate content issues.", example: "A product page accessible at both ?sort=new and the default URL should canonical to the default.", category: "seo" }),
  T({ term: "Hreflang", shortDef: "Tells Google which language a page is in.", definition: "Hreflang is an HTML attribute that tells Google which language and region a page targets. Essential for multi-language sites to serve the right version to users.", example: "<link rel=\"alternate\" hreflang=\"fr\" href=\"https://example.com/fr/page\" />", category: "seo" }),
  T({ term: "Backlink", shortDef: "A link from another site to yours.", definition: "A backlink (inbound link) is a link from another website to your site. Backlinks from authoritative sites are one of Google's strongest ranking signals.", category: "seo" }),
  T({ term: "Domain authority", shortDef: "A site's overall ranking strength (Moz metric).", definition: "Domain Authority (DA) is Moz's proprietary score (0-100) predicting how well a site will rank. Google doesn't use DA, but it's a useful proxy for overall SEO strength.", category: "seo" }),
  T({ term: "Page authority", shortDef: "A single page's ranking strength.", definition: "Page Authority (PA) is Moz's per-page score predicting ranking ability. Similar to DA but for individual URLs.", category: "seo" }),
  T({ term: "PageRank", shortDef: "Google's original link-based ranking algorithm.", definition: "PageRank is the algorithm Google was founded on — measuring a page's importance by the links pointing to it. Still part of Google's ranking system, though heavily evolved.", category: "seo" }),
  T({ term: "Internal link", shortDef: "A link between pages on the same site.", definition: "Internal linking is how you connect pages on your own site. Strong internal linking distributes PageRank, helps Google understand site structure, and improves user navigation.", category: "seo" }),
  T({ term: "Anchor text", shortDef: "The clickable text of a link.", definition: "Anchor text is the visible, clickable text of a hyperlink. It gives Google context about the linked page. Exact-match anchors are powerful but can be spammy if overused.", category: "seo" }),
  T({ term: "NoFollow", shortDef: "Tells search engines not to follow/credit a link.", definition: "rel=\"nofollow\" tells search engines not to pass ranking credit through a link. Use on paid, UGC, or untrusted links.", category: "seo" }),
  T({ term: "Schema markup", shortDef: "Structured data for rich results.", definition: "Schema markup (schema.org vocabulary) is structured data that helps search engines understand page content. When added via JSON-LD, it enables rich results like stars, FAQs, and product info.", category: "seo" }),
  T({ term: "JSON-LD", shortDef: "Schema markup format.", definition: "JSON-LD (JavaScript Object Notation for Linked Data) is Google's preferred format for adding schema markup. Added via <script type=\"application/ld+json\">.", category: "seo" }),
  T({ term: "Structured data", shortDef: "Machine-readable page info.", definition: "Structured data is a standardized format for providing information about a page and classifying its content — typically via schema.org markup.", category: "seo" }),
  T({ term: "Rich results", shortDef: "Enhanced SERP listings.", definition: "Rich results (formerly rich snippets) are visually enhanced search listings — star ratings, prices, FAQs, videos, and more. Triggered by structured data.", category: "seo" }),
  T({ term: "Robots.txt", shortDef: "File telling crawlers what to access.", definition: "robots.txt is a text file at your site root that tells search engine crawlers which pages they can or cannot crawl. Not a security measure — just a politeness request.", category: "seo" }),
  T({ term: "XML sitemap", shortDef: "List of site URLs for crawlers.", definition: "An XML sitemap is a file listing all your site's URLs to help search engines discover them. Submit it in Google Search Console for faster indexing.", category: "seo" }),
  T({ term: "Crawl budget", shortDef: "How many pages Google will crawl per visit.", definition: "Crawl budget is the number of URLs Googlebot will crawl on your site within a given timeframe. Large sites need to optimize which pages Google spends time on.", category: "seo" }),
  T({ term: "Indexation", shortDef: "Getting pages into Google's index.", definition: "Indexation is the process of Google storing your pages in its index. A page has to be indexed to rank. Check index status in Google Search Console.", category: "seo" }),
  T({ term: "Google Search Console", shortDef: "Google's webmaster tools.", definition: "Google Search Console (GSC) is Google's free tool for monitoring your site's presence in Google search. Submit sitemaps, fix errors, see queries, and track impressions/clicks.", category: "seo" }),
  T({ term: "Core Web Vitals", shortDef: "Google's user experience metrics.", definition: "Core Web Vitals are three metrics Google uses as a ranking factor: LCP (loading), INP (interactivity), and CLS (visual stability). Measured in Google Search Console.", category: "technical" }),
  T({ term: "LCP", shortDef: "Largest contentful paint — page load metric.", definition: "Largest Contentful Paint (LCP) is the time from page load start until the largest image/text block is visible. Good: <2.5s. Poor: >4s.", category: "technical" }),
  T({ term: "CLS", shortDef: "Cumulative layout shift — visual stability metric.", definition: "Cumulative Layout Shift (CLS) measures how much content jumps around during page load. Good: <0.1. Reserve space for images/ads to improve.", category: "technical" }),
  T({ term: "INP", shortDef: "Interaction to next paint — responsiveness metric.", definition: "Interaction to Next Paint (INP) measures how quickly a page responds to user interactions. Replaced FID in 2024. Good: <200ms.", category: "technical" }),
  T({ term: "TTFB", shortDef: "Time to first byte — server response speed.", definition: "Time to First Byte (TTFB) is how long the browser waits before receiving the first byte from the server. Good: <800ms. Affects LCP directly.", category: "technical" }),

  // === CONTENT MARKETING ===
  T({ term: "Content marketing", shortDef: "Creating content to attract customers.", definition: "Content marketing is a strategy of creating and distributing valuable content (blogs, videos, podcasts) to attract and convert customers. More sustainable than paid ads but takes longer.", category: "marketing" }),
  T({ term: "Pillar page", shortDef: "In-depth guide on a broad topic.", definition: "A pillar page is a long-form (3000+ word) guide covering a broad topic comprehensively. Supporting cluster content links to it, creating a topic cluster for SEO.", category: "content" }),
  T({ term: "Topic cluster", shortDef: "Group of related pages linked to a pillar.", definition: "A topic cluster is a pillar page plus multiple supporting articles (cluster content) all internally linked. This structure signals topical authority to Google.", category: "content" }),
  T({ term: "Evergreen content", shortDef: "Content that stays relevant for years.", definition: "Evergreen content is content that remains relevant and useful over time — like \"how to write a blog post\" vs \"best blog tools 2023\". Highest ROI type of content.", category: "content" }),
  T({ term: "Skyscraper content", shortDef: "Longer, better version of top-ranking content.", definition: "The Skyscraper Technique (Brian Dean) involves finding the top-ranking content for a keyword and creating a significantly better, longer, more comprehensive version.", category: "content" }),
  T({ term: "Content calendar", shortDef: "Schedule of planned content.", definition: "A content calendar is a schedule showing what content will be published when. Helps coordinate topics, keywords, and team workflows.", category: "content" }),
  T({ term: "Editorial calendar", shortDef: "Content calendar for a publication.", definition: "An editorial calendar is a more detailed content calendar for media operations — includes assignees, reviewers, publish dates, topic clusters, and approval stages.", category: "content" }),
  T({ term: "Content gap analysis", shortDef: "Finding topics competitors rank for but you don't.", definition: "Content gap analysis identifies keywords competitors rank for that you don't. Fill the gaps to steal their traffic. Tools: Ahrefs, Semrush, or RankFlo's competitive analysis.", category: "content" }),
  T({ term: "Content pruning", shortDef: "Deleting or improving low-performing content.", definition: "Content pruning is the practice of removing or consolidating underperforming pages. Helps crawl budget, focuses authority on remaining pages, and improves overall site quality.", category: "content" }),
  T({ term: "Listicle", shortDef: "A numbered list article.", definition: "A listicle (list + article) is a post structured as a numbered list — \"10 ways to…\", \"Top 25 X\". Highly shareable, often rank well for \"best of\" queries.", category: "content" }),
  T({ term: "How-to content", shortDef: "Step-by-step instructional content.", definition: "How-to content teaches readers to accomplish a task. Highly valuable for SEO — targets \"how to X\" queries which are massive in volume.", category: "content" }),
  T({ term: "Pillar-and-cluster", shortDef: "Content strategy built on topic authority.", definition: "Pillar-and-cluster is a content model: one pillar page broadly covers a topic, cluster pages go deep on subtopics, and all internally link. Signals topical authority.", category: "content" }),

  // === CMS / TECHNICAL ===
  T({ term: "CMS", shortDef: "Content management system.", definition: "A Content Management System (CMS) is software for creating, managing, and publishing digital content without coding. Examples: WordPress, Ghost, Contentful, RankFlo.", category: "cms" }),
  T({ term: "Headless CMS", shortDef: "CMS with API, no front-end rendering.", definition: "A headless CMS separates content management from front-end rendering. Content lives in the CMS, but any frontend (Next.js, React, mobile app) consumes it via API.", example: "Contentful, Sanity, RankFlo, and Strapi are headless CMSs.", category: "cms" }),
  T({ term: "Hybrid CMS", shortDef: "Combines headless + traditional rendering.", definition: "A hybrid CMS offers both: API access (like headless) AND built-in themes/rendering (like traditional). Gives flexibility with less upfront work. RankFlo is a hybrid CMS.", category: "cms" }),
  T({ term: "Static site generator", shortDef: "Builds HTML files at deploy time.", definition: "A Static Site Generator (SSG) builds your site as static HTML/CSS/JS at deploy time. No server at runtime. Examples: Hugo, Jekyll, Astro, Next.js static export.", category: "cms" }),
  T({ term: "Jamstack", shortDef: "Modern web architecture (JavaScript, APIs, Markup).", definition: "Jamstack is an architecture philosophy: prebuilt Markup delivered via CDN, with dynamic features via JavaScript and APIs. Fast, secure, cheap to host.", category: "cms" }),
  T({ term: "API-first", shortDef: "API is the primary interface.", definition: "API-first means the software is designed around its API rather than a UI. Any frontend can consume it. RankFlo is API-first.", category: "cms" }),
  T({ term: "Multi-tenant", shortDef: "One app serves multiple isolated customers.", definition: "Multi-tenant software serves multiple organizations from a single instance, with data isolation between them. RankFlo is multi-tenant — each organization's content is isolated.", category: "cms" }),
  T({ term: "Multi-site", shortDef: "One installation manages multiple websites.", definition: "Multi-site CMSs let one installation manage multiple distinct websites. Useful for agencies managing multiple client blogs or brands.", category: "cms" }),
  T({ term: "RBAC", shortDef: "Role-based access control.", definition: "Role-Based Access Control (RBAC) gives users permissions based on their role (admin, editor, author, viewer). Essential for team CMSs.", category: "cms" }),
  T({ term: "Webhooks", shortDef: "HTTP callbacks for events.", definition: "Webhooks are HTTP callbacks that fire when events happen in a system. E.g., a CMS can fire a webhook to trigger your static site to rebuild on publish.", category: "technical" }),
  T({ term: "Incremental static regeneration", shortDef: "Rebuild individual pages on-demand.", definition: "Incremental Static Regeneration (ISR) is a Next.js feature that regenerates individual static pages on-demand when content changes, without rebuilding the whole site.", category: "technical" }),
  T({ term: "Static site generation", shortDef: "Pre-build all pages as HTML.", definition: "Static Site Generation (SSG) pre-builds all pages as HTML at build time. Maximum performance and cacheability, but rebuilds needed for content changes.", category: "technical" }),
  T({ term: "Server-side rendering", shortDef: "Render HTML on the server per request.", definition: "Server-Side Rendering (SSR) renders HTML on the server for each request. Good for dynamic content. Slower than SSG but always fresh.", category: "technical" }),
  T({ term: "Client-side rendering", shortDef: "JavaScript renders HTML in the browser.", definition: "Client-Side Rendering (CSR) ships empty HTML + JS; the browser renders the content. Bad for SEO unless hydrated with SSR first. Common in single-page apps.", category: "technical" }),
  T({ term: "React Server Components", shortDef: "React components that run only on the server.", definition: "React Server Components (RSC) run exclusively on the server — no JS shipped to the browser. Next.js App Router uses RSC by default. Great for SEO + performance.", category: "technical" }),
  T({ term: "Edge computing", shortDef: "Compute at the network edge, close to users.", definition: "Edge computing runs code close to users geographically (via CDN PoPs). Faster than centralized servers. Examples: Vercel Edge Runtime, Cloudflare Workers.", category: "technical" }),
  T({ term: "CDN", shortDef: "Content delivery network.", definition: "A CDN is a network of servers worldwide that cache your site's content close to users. Reduces latency. Examples: Cloudflare, Vercel, Fastly.", category: "technical" }),
  T({ term: "Tiptap", shortDef: "Rich-text editor framework for React/Vue.", definition: "Tiptap is a headless editor framework built on ProseMirror. Used by RankFlo, Notion-like tools, and many modern CMSs for rich-text content editing.", category: "technical" }),
  T({ term: "ProseMirror", shortDef: "Editor toolkit underlying Tiptap.", definition: "ProseMirror is a toolkit for building rich-text editors with custom schemas. Tiptap is a React wrapper around it.", category: "technical" }),
  T({ term: "Markdown", shortDef: "Lightweight markup language.", definition: "Markdown is a plain-text format for writing with formatting (# for headings, ** for bold). Renders to HTML. Popular in developer blogs and README files.", category: "technical" }),
  T({ term: "MDX", shortDef: "Markdown + JSX components.", definition: "MDX lets you use JSX components inside Markdown. Popular in developer docs where you want interactive components embedded in prose content.", category: "technical" }),

  // === ANALYTICS ===
  T({ term: "Bounce rate", shortDef: "Percentage of single-page visits.", definition: "Bounce rate is the percentage of sessions where a user views only one page before leaving. High bounce rate can signal bad content match or UX issues — but it's complicated.", category: "analytics" }),
  T({ term: "CTR", shortDef: "Click-through rate.", definition: "Click-Through Rate (CTR) is the percentage of impressions that result in clicks. In SEO, it's the ratio of SERP clicks to impressions. Ads, emails, and buttons also have CTR.", category: "analytics" }),
  T({ term: "Impressions", shortDef: "Number of times content was shown.", definition: "Impressions count how many times your content appeared to users — in search results, ads, or feeds. Not the same as views (which require actual engagement).", category: "analytics" }),
  T({ term: "Page views", shortDef: "Number of times a page was loaded.", definition: "Page views count how many times a page was loaded. Different from unique visitors (one visitor can create multiple page views).", category: "analytics" }),
  T({ term: "Sessions", shortDef: "A user's visit to your site.", definition: "A session is a group of user interactions on your site within a time window (typically 30 minutes). One user can have multiple sessions. Used in analytics like GA4.", category: "analytics" }),
  T({ term: "Cookieless analytics", shortDef: "Analytics without browser cookies.", definition: "Cookieless analytics tracks visitors without setting cookies — respecting privacy and GDPR. Examples: Plausible, Fathom, RankFlo's built-in analytics.", category: "analytics" }),

  // === AI / LLM ===
  T({ term: "GEO", shortDef: "Generative engine optimization.", definition: "Generative Engine Optimization (GEO) is SEO for AI answer engines like ChatGPT, Perplexity, and Claude. Focuses on getting cited in AI-generated answers, not just ranking in Google.", category: "ai" }),
  T({ term: "LLM", shortDef: "Large language model.", definition: "A Large Language Model (LLM) is an AI trained on massive text corpora to generate human-like text. Examples: GPT-5, Claude 4.7 Opus, Gemini 2.5.", category: "ai" }),
  T({ term: "RAG", shortDef: "Retrieval-augmented generation.", definition: "Retrieval-Augmented Generation (RAG) is an AI technique where a model retrieves relevant documents before generating an answer. Used by Perplexity, ChatGPT web search, and many enterprise LLM apps.", category: "ai" }),
  T({ term: "llms.txt", shortDef: "Spec for giving LLMs structured site info.", definition: "llms.txt is a proposed standard (similar to robots.txt) that gives LLMs a structured, markdown-formatted summary of your site. Helps AI crawlers cite you correctly.", category: "ai" }),
  T({ term: "AI overview", shortDef: "Google's AI-generated answers in SERPs.", definition: "AI Overviews (formerly SGE) are Google's AI-generated answers at the top of search results. Changes SEO — clicks may drop unless your content gets cited.", category: "ai" }),
  T({ term: "ChatGPT", shortDef: "OpenAI's flagship AI chatbot.", definition: "ChatGPT is OpenAI's AI chatbot powered by GPT models. Handles text generation, coding, research, and more. Now a major source of traffic for publishers via citations.", category: "ai" }),
  T({ term: "Claude", shortDef: "Anthropic's AI assistant.", definition: "Claude is Anthropic's AI assistant. The Claude 4.X family — Opus 4.7, Sonnet 4.6, Haiku 4.5 — is known for long context windows (up to 1M tokens) and strong reasoning.", category: "ai" }),
  T({ term: "Perplexity", shortDef: "AI-powered search engine.", definition: "Perplexity is an AI search engine that answers queries with citations to source websites. A major traffic driver for content sites that get cited.", category: "ai" }),
  T({ term: "Prompt engineering", shortDef: "Writing effective prompts for LLMs.", definition: "Prompt engineering is the art of writing instructions to LLMs to get desired outputs. Key skill for using ChatGPT, Claude, or building AI features.", category: "ai" }),
  T({ term: "Hallucination", shortDef: "AI making up incorrect information.", definition: "An AI hallucination is when an LLM generates confident-sounding but incorrect or fabricated information. Mitigated by RAG, citations, and careful prompting.", category: "ai" }),
  T({ term: "Context window", shortDef: "How much text an LLM can process at once.", definition: "Context window is the maximum amount of text (in tokens) an LLM can process in a single conversation. Claude Opus 4.7 supports 1M tokens. GPT-5 supports up to 200k.", category: "ai" }),
  T({ term: "Embedding", shortDef: "Numerical vector representing text meaning.", definition: "An embedding is a numerical vector representing a piece of text's semantic meaning. Used for similarity search, RAG, and recommendation systems.", category: "ai" }),
  T({ term: "Semantic search", shortDef: "Search based on meaning, not keywords.", definition: "Semantic search matches queries to documents based on meaning (via embeddings) rather than exact keyword matches. What modern AI-powered search uses.", category: "ai" }),

  // === MORE SEO DETAILS ===
  T({ term: "301 redirect", shortDef: "Permanent redirect.", definition: "A 301 redirect is an HTTP response permanently redirecting one URL to another. Passes ~90-99% of link equity. Use when permanently moving content.", category: "seo" }),
  T({ term: "302 redirect", shortDef: "Temporary redirect.", definition: "A 302 redirect is a temporary URL redirect. Generally doesn't pass link equity. Use 301 unless the move is truly temporary.", category: "seo" }),
  T({ term: "Breadcrumbs", shortDef: "Navigation showing page hierarchy.", definition: "Breadcrumbs are a navigation aid showing a page's hierarchy (e.g., Home > Blog > Category > Post). Can also be a structured data schema for rich results.", category: "seo" }),
  T({ term: "Alt text", shortDef: "Image description for accessibility + SEO.", definition: "Alt text describes an image for screen readers and when images fail to load. Also helps image SEO — Google uses alt text to understand images.", category: "seo" }),
  T({ term: "Open Graph", shortDef: "Meta tags controlling social share cards.", definition: "Open Graph (OG) is a protocol (from Facebook) using meta tags to control how URLs appear when shared on social media. og:title, og:description, og:image are the main ones.", category: "seo" }),
  T({ term: "OG image", shortDef: "Image shown in social share cards.", definition: "An Open Graph image (og:image) is the thumbnail shown when your URL is shared on social. Recommended: 1200×630 pixels. Dynamically generated OG images are increasingly common.", category: "seo" }),
  T({ term: "Twitter card", shortDef: "Twitter's social share card format.", definition: "Twitter Cards are Twitter's format for rich share previews. twitter:card, twitter:title, etc. Usually summary_large_image uses the same image as OG.", category: "seo" }),
  T({ term: "Favicon", shortDef: "Small icon shown in browser tabs.", definition: "A favicon is the small icon shown in browser tabs and bookmarks. Modern sites should provide multiple sizes for different devices and contexts.", category: "seo" }),
  T({ term: "Keyword density", shortDef: "% of page text that's a target keyword.", definition: "Keyword density is the percentage of page text made up of a target keyword. 1-2% is a rough guideline. Excessive density triggers keyword stuffing penalties.", category: "seo" }),
  T({ term: "Keyword stuffing", shortDef: "Over-using keywords unnaturally.", definition: "Keyword stuffing is the practice of repeating keywords unnaturally to manipulate rankings. Penalized by Google. Write naturally — focus on semantic relevance.", category: "seo" }),
  T({ term: "Cloaking", shortDef: "Showing different content to crawlers vs users.", definition: "Cloaking is showing different content to search engine crawlers than to human users to manipulate rankings. Violates Google's guidelines — will get you penalized.", category: "seo" }),
  T({ term: "E-E-A-T", shortDef: "Experience, Expertise, Authoritativeness, Trust.", definition: "E-E-A-T is Google's quality framework: Experience, Expertise, Authoritativeness, and Trustworthiness. Important for YMYL topics. Signal it via author pages, citations, and credentials.", category: "seo" }),
  T({ term: "YMYL", shortDef: "Your Money, Your Life topics.", definition: "YMYL (Your Money or Your Life) is Google's classification for topics affecting users' wellbeing — finance, health, legal. Held to higher quality standards.", category: "seo" }),
  T({ term: "Core update", shortDef: "Broad change to Google's ranking algorithm.", definition: "A core update is Google's periodic broad adjustment to its ranking algorithm. Can cause significant ranking changes. Not targeting specific sites — just re-evaluating content quality.", category: "seo" }),
  T({ term: "Google Panda", shortDef: "2011 update targeting low-quality content.", definition: "Google Panda was a 2011 algorithm update targeting thin/low-quality content. Now part of core algorithm. Inspired focus on content quality.", category: "seo" }),
  T({ term: "Google Penguin", shortDef: "2012 update targeting spammy links.", definition: "Google Penguin was a 2012 algorithm update targeting manipulative link building. Also now part of the core algorithm. Ushered in the era of safer link strategies.", category: "seo" }),
  T({ term: "Helpful Content Update", shortDef: "Google's 2022 content quality update.", definition: "Google's Helpful Content Update (2022) targets sites with large amounts of unhelpful, AI-generated, or SEO-first (rather than user-first) content.", category: "seo" }),

  // === MORE CMS / TECH ===
  T({ term: "Monolith CMS", shortDef: "Tightly coupled CMS + frontend.", definition: "A monolith CMS combines content management and front-end rendering tightly (e.g., WordPress). Simple to set up but hard to customize and slow compared to headless architectures.", category: "cms" }),
  T({ term: "Decoupled CMS", shortDef: "Separated backend + presentation.", definition: "A decoupled CMS separates the backend (content management) from the presentation layer (frontend). Similar to headless but with optional built-in rendering.", category: "cms" }),
  T({ term: "Git-based CMS", shortDef: "CMS where content lives in a git repo.", definition: "A git-based CMS stores content in a git repository (often as Markdown). Examples: Netlify CMS, Tina, Forestry. Good for developer blogs, limited for non-technical authors.", category: "cms" }),
  T({ term: "Content federation", shortDef: "Combining content from multiple sources.", definition: "Content federation combines content from multiple sources (different CMSs, databases, APIs) into one unified content layer. Used by large enterprises like Hygraph.", category: "cms" }),
  T({ term: "Content modeling", shortDef: "Defining content structure.", definition: "Content modeling is the process of defining content types, fields, and relationships in a CMS (e.g., \"a Blog Post has a title, author, tags\"). Foundation of any CMS implementation.", category: "cms" }),
  T({ term: "Block editor", shortDef: "Editor where content is in blocks.", definition: "A block editor treats each piece of content (paragraph, image, heading) as a discrete block. Popularized by Gutenberg (WordPress), Notion, and Tiptap. Default in modern CMSs.", category: "cms" }),
  T({ term: "WYSIWYG", shortDef: "What You See Is What You Get editor.", definition: "WYSIWYG (what you see is what you get) editors show formatted content as it will appear on the live site. Modern CMSs use block editors instead, which are more structured.", category: "cms" }),

  // === MARKETING ===
  T({ term: "CTA", shortDef: "Call to action.", definition: "A Call To Action (CTA) is a prompt telling users what to do next — \"Sign up\", \"Download\", \"Learn more\". Good CTAs are specific, action-oriented, and visually prominent.", category: "marketing" }),
  T({ term: "Lead magnet", shortDef: "Free offer in exchange for an email.", definition: "A lead magnet is a free resource (ebook, template, guide) offered in exchange for an email address. Core tool in content marketing for list building.", category: "marketing" }),
  T({ term: "Conversion rate", shortDef: "% of visitors who take a desired action.", definition: "Conversion rate is the percentage of visitors who take a desired action (sign up, purchase, download). Key SaaS metric.", category: "marketing" }),
  T({ term: "Funnel", shortDef: "Path from visitor to customer.", definition: "A marketing funnel is the journey from first visit to customer — awareness → interest → consideration → purchase. Measure drop-off at each stage.", category: "marketing" }),
  T({ term: "Inbound marketing", shortDef: "Attract customers via helpful content.", definition: "Inbound marketing is a methodology of attracting customers by creating valuable content and experiences tailored to them — instead of interrupting them with ads.", category: "marketing" }),
  T({ term: "Product-led growth", shortDef: "Product itself drives adoption.", definition: "Product-Led Growth (PLG) uses the product itself as the primary driver of user acquisition, conversion, and expansion. Typically via free tiers, self-serve signup, and viral features.", category: "marketing" }),
]);

export const ALL_GLOSSARY_SLUGS = Object.keys(GLOSSARY);

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY[slug];
}

export const GLOSSARY_CATEGORIES = ["seo", "content", "cms", "analytics", "ai", "technical", "marketing"] as const;
