// Product catalog — powers /compare, /alternatives, and cross-references in /blog
// Each product is a separate SEO target.

export type ProductCategory =
  | "blog-cms"
  | "headless-cms"
  | "newsletter"
  | "website-builder"
  | "docs-platform"
  | "static-site-generator"
  | "notes-publishing";

export interface Product {
  slug: string;
  name: string;
  category: ProductCategory;
  tagline: string;
  description: string;
  pros: string[];
  cons: string[];
  pricingSummary: string;
  openSource: boolean;
  selfHosted: boolean;
  aiBuiltIn: boolean;
  headlessApi: boolean;
  customDomain: boolean;
  bestFor: string;
}

export const PRODUCTS: Record<string, Product> = {
  wordpress: {
    slug: "wordpress",
    name: "WordPress",
    category: "blog-cms",
    tagline: "The world's most popular CMS",
    description: "WordPress powers over 40% of the web. Massive plugin ecosystem, theme marketplace, and decades of community support — but heavy, plugin-dependent, and expensive to keep secure.",
    pros: ["Huge plugin ecosystem", "Thousands of themes", "Decades of community", "Low learning curve for admins"],
    cons: ["Plugin security risks", "Slow without caching", "PHP-based, dated stack", "Plugin subscription costs add up"],
    pricingSummary: "Self-hosted free; WordPress.com $4-45/mo; hosting $5-50/mo",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "non-technical teams wanting maximum flexibility",
  },
  ghost: {
    slug: "ghost",
    name: "Ghost",
    category: "blog-cms",
    tagline: "Professional publishing platform",
    description: "Ghost is a Node.js-based publishing platform built for professional creators. Clean editor, built-in newsletter, membership monetization — but closed ecosystem, limited extensibility.",
    pros: ["Beautiful editor", "Built-in newsletter & paid subs", "Fast performance", "MIT licensed"],
    cons: ["Limited plugin ecosystem", "No AI built-in", "Ghost(Pro) pricey at scale", "Theme marketplace small"],
    pricingSummary: "Self-hosted free; Ghost(Pro) $9-199/mo",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "solo creators and newsletter-focused publishers",
  },
  medium: {
    slug: "medium",
    name: "Medium",
    category: "blog-cms",
    tagline: "Publish on a shared network",
    description: "Medium gives you instant audience access via its partner network but you don't own your domain, data, or readers. Paywall system restricts non-members.",
    pros: ["Built-in audience", "Zero setup", "Clean reading UX", "Partner program payouts"],
    cons: ["No custom domain on free", "Platform lock-in", "Paywall hides your content", "Limited SEO control"],
    pricingSummary: "Free to publish; $5/mo membership for readers",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: false,
    bestFor: "writers who want audience, not ownership",
  },
  substack: {
    slug: "substack",
    name: "Substack",
    category: "newsletter",
    tagline: "Newsletter + light blog",
    description: "Substack dominates email-first publishing with built-in subscriptions and discovery network. Takes 10% of paid subscriptions. Limited blog/SEO features.",
    pros: ["Email delivery included", "Subscription billing built-in", "Discovery network", "Simple writer UX"],
    cons: ["10% take rate on paid subs", "Limited SEO/blog design", "No custom domain on free", "Locked into their platform"],
    pricingSummary: "Free; 10% + Stripe fees on paid subs",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "newsletter writers monetizing via subscriptions",
  },
  hashnode: {
    slug: "hashnode",
    name: "Hashnode",
    category: "blog-cms",
    tagline: "Developer blogging community",
    description: "Hashnode is a blogging platform designed for developers with a built-in community, custom domains on free tier, and GitHub integration.",
    pros: ["Free custom domain", "Developer community", "GitHub auth", "Newsletter built-in"],
    cons: ["Closed source", "Limited customization", "No self-hosting", "GraphQL-only API"],
    pricingSummary: "Free tier + $199/mo business",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "individual developers seeking community exposure",
  },
  contentful: {
    slug: "contentful",
    name: "Contentful",
    category: "headless-cms",
    tagline: "Enterprise headless CMS",
    description: "Contentful is a powerful general-purpose headless CMS used by large enterprises. Flexible content modeling but expensive and over-engineered for simple blogs.",
    pros: ["Flexible content model", "Enterprise-grade CDN", "Big ecosystem", "Great DX for large teams"],
    cons: ["Starts at $300/mo for teams", "Overkill for blogs", "Steep learning curve", "No built-in AI/analytics"],
    pricingSummary: "Free starter; Team $300/mo; Premium custom",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "large enterprises with complex content models",
  },
  strapi: {
    slug: "strapi",
    name: "Strapi",
    category: "headless-cms",
    tagline: "Open-source headless CMS",
    description: "Strapi is the leading open-source headless CMS with a flexible content type builder and self-hosting. General-purpose — needs setup for blogging.",
    pros: ["Open source & self-hostable", "Content type builder", "Plugin marketplace", "REST + GraphQL"],
    cons: ["Requires DevOps setup", "Not blog-optimized", "No AI content built-in", "Enterprise features paid"],
    pricingSummary: "Self-hosted free; Cloud $9-99/mo; Enterprise custom",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "developers building custom content structures",
  },
  sanity: {
    slug: "sanity",
    name: "Sanity",
    category: "headless-cms",
    tagline: "Structured content platform",
    description: "Sanity offers real-time collaborative content modeling with the powerful GROQ query language. Flexible and developer-friendly but requires configuration.",
    pros: ["Real-time collaboration", "Flexible schema", "GROQ query language", "Customizable Studio"],
    cons: ["Requires setup per use case", "No self-hosting", "Pricing ramps quickly", "No built-in blog/SEO"],
    pricingSummary: "Free tier; Growth $99/mo; Business custom",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "product teams with custom content needs",
  },
  webflow: {
    slug: "webflow",
    name: "Webflow",
    category: "website-builder",
    tagline: "Visual website builder",
    description: "Webflow lets designers build responsive sites visually, with a CMS for basic blog collections. Great design control, but expensive at scale and limited for pure blogging.",
    pros: ["Visual design freedom", "Clean code output", "Hosting included", "Good for marketing sites"],
    cons: ["Expensive CMS items", "Limited AI/SEO tools", "Lock-in to Webflow hosting", "Poor for large blogs"],
    pricingSummary: "Site plans $14-39/mo; CMS tier $23+/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "design-first marketing sites with light blogging",
  },
  wix: {
    slug: "wix",
    name: "Wix",
    category: "website-builder",
    tagline: "Drag-and-drop website builder",
    description: "Wix is the mass-market website builder with templates for every use case. The blog is an add-on — suitable for very small sites but limited for serious content work.",
    pros: ["Easy drag-and-drop", "Hundreds of templates", "Hosting included", "App market"],
    cons: ["Bloated code output", "Weak SEO by default", "Limited blog/CMS features", "Can't export site"],
    pricingSummary: "$16-159/mo depending on plan",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "small business websites needing a simple blog",
  },
  squarespace: {
    slug: "squarespace",
    name: "Squarespace",
    category: "website-builder",
    tagline: "All-in-one website platform",
    description: "Squarespace offers elegant templates and an all-in-one hosting + site builder. Blog features are basic, and SEO control is limited compared to dedicated CMSs.",
    pros: ["Beautiful templates", "All-in-one hosting", "Commerce tools", "Custom domains"],
    cons: ["Template lock-in", "Limited SEO control", "Weak blog features", "Transfer is hard"],
    pricingSummary: "$16-52/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "designers and creative professionals with portfolios",
  },
  notion: {
    slug: "notion",
    name: "Notion",
    category: "notes-publishing",
    tagline: "Notes and wiki with public publishing",
    description: "Notion pages can be published publicly, making it a lightweight blog. But you give up SEO control, custom domains (without workarounds), and ownership.",
    pros: ["Great editor", "All-in-one workspace", "Fast to publish", "Free tier"],
    cons: ["Limited SEO control", "No native custom domain", "Slow page loads", "Not purpose-built for blogs"],
    pricingSummary: "Free; Plus $8/mo; Business $15/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: true,
    headlessApi: true,
    customDomain: false,
    bestFor: "teams using Notion internally who want casual publishing",
  },
  beehiiv: {
    slug: "beehiiv",
    name: "Beehiiv",
    category: "newsletter",
    tagline: "Newsletter platform with growth tools",
    description: "Beehiiv is a Substack alternative with better analytics, referral programs, and a more generous free plan. Growing fast with email-first creators.",
    pros: ["Free to 2500 subs", "Built-in referral program", "Better analytics than Substack", "Ad network"],
    cons: ["Email-first, weak blog", "No self-hosting", "Limited SEO features", "No AI writing tools"],
    pricingSummary: "Free to 2500; $49+/mo beyond",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "newsletter-first creators optimizing growth",
  },
  convertkit: {
    slug: "convertkit",
    name: "Kit (ConvertKit)",
    category: "newsletter",
    tagline: "Email for creators",
    description: "Kit (formerly ConvertKit) is a creator-focused email platform with automation, landing pages, and commerce. The blog/publishing piece is secondary.",
    pros: ["Best-in-class email automation", "Creator commerce", "Landing pages", "Tagging system"],
    cons: ["Email-first, not a blog", "No custom CMS", "No SEO tools", "Pricing scales fast"],
    pricingSummary: "Free to 10k; $15-90/mo paid",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "email-first creators with product sales",
  },
  payload: {
    slug: "payload",
    name: "Payload",
    category: "headless-cms",
    tagline: "TypeScript-native headless CMS",
    description: "Payload is a self-hostable, TypeScript-first headless CMS with a flexible admin UI. Developer-friendly but requires more setup than dedicated blog platforms.",
    pros: ["TypeScript-native", "Self-hostable", "Flexible admin UI", "Node.js + MongoDB/Postgres"],
    cons: ["Not blog-optimized", "No built-in AI/analytics", "Learning curve", "No managed option at scale"],
    pricingSummary: "Self-hosted free; Cloud $35-299/mo",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "TypeScript teams building custom apps",
  },
  directus: {
    slug: "directus",
    name: "Directus",
    category: "headless-cms",
    tagline: "Data platform over any SQL database",
    description: "Directus provides instant APIs and admin apps on top of any existing SQL database. Highly flexible but requires schema design and isn't a turnkey blog.",
    pros: ["Works with existing DBs", "SQL-first", "Open source", "Flexible"],
    cons: ["Not blog-focused", "Requires DBA skills", "No AI content tools", "Complex for small teams"],
    pricingSummary: "Self-hosted free; Cloud $15-99/mo",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "teams with existing SQL databases needing APIs",
  },
  prismic: {
    slug: "prismic",
    name: "Prismic",
    category: "headless-cms",
    tagline: "Slice-based headless CMS",
    description: "Prismic's slice machine lets marketers compose pages from reusable components. Strong for landing pages and marketing but not blog-specialized.",
    pros: ["Slice-based page building", "Visual editor", "Slice machine DX", "Good DX for developers"],
    cons: ["Not blog-optimized", "Pricing scales fast", "No self-hosting", "No AI built-in"],
    pricingSummary: "Free; Starter $7/mo; Business $150+/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "marketing teams building modular landing pages",
  },
  storyblok: {
    slug: "storyblok",
    name: "Storyblok",
    category: "headless-cms",
    tagline: "Visual editor headless CMS",
    description: "Storyblok offers a visual editor on top of a headless CMS — unusual combo that lets marketers preview changes visually while developers keep flexibility.",
    pros: ["Visual editor", "Great DX", "Strong component system", "Enterprise plans"],
    cons: ["Pricing scales fast", "No self-hosting", "Learning curve", "Not blog-first"],
    pricingSummary: "Free; Business $423/mo; Enterprise custom",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "marketing teams wanting visual editing with headless APIs",
  },
  datocms: {
    slug: "datocms",
    name: "DatoCMS",
    category: "headless-cms",
    tagline: "Headless CMS for modern sites",
    description: "DatoCMS is a polished headless CMS with GraphQL API and a clean admin UI. Good general-purpose choice but lacks blog-specific features and costs more.",
    pros: ["Polished admin UI", "GraphQL API", "Image transforms", "Good DX"],
    cons: ["No self-hosting", "Pricing scales fast", "Not blog-optimized", "No AI built-in"],
    pricingSummary: "Free dev; $149+/mo paid",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "design-driven teams needing a polished CMS",
  },
  buttercms: {
    slug: "buttercms",
    name: "ButterCMS",
    category: "headless-cms",
    tagline: "Blog CMS as a service",
    description: "ButterCMS is a SaaS blog engine you plug into any app via API. Solves the 'add a blog' use case simply but lacks advanced CMS features and self-hosting.",
    pros: ["Simple blog API", "Fast to integrate", "SDKs for most frameworks", "Good for devs"],
    cons: ["Closed source", "No self-hosting", "Limited customization", "No AI built-in"],
    pricingSummary: "$99-299/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "developers needing a drop-in blog API",
  },
  hygraph: {
    slug: "hygraph",
    name: "Hygraph",
    category: "headless-cms",
    tagline: "GraphQL-first headless CMS",
    description: "Hygraph (formerly GraphCMS) provides a GraphQL-native headless CMS with content federation. Powerful but overkill for most blog use cases.",
    pros: ["GraphQL-native", "Content federation", "Strong team features", "Localization"],
    cons: ["Not blog-focused", "Pricing scales fast", "No self-hosting", "No AI built-in"],
    pricingSummary: "Free; Growth $299+/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "teams adopting GraphQL federation",
  },
  blogger: {
    slug: "blogger",
    name: "Blogger",
    category: "blog-cms",
    tagline: "Google's free blogging platform",
    description: "Blogger is Google's free blog host. Zero cost, zero flexibility. Largely unmaintained and lacks modern features, but still works for the simplest blogs.",
    pros: ["Free forever", "Google-hosted", "Zero setup", "Adsense integration"],
    cons: ["Dated interface", "Very limited SEO", "No modern features", "Google could sunset"],
    pricingSummary: "Free",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "personal hobby blogs with zero budget",
  },
  tumblr: {
    slug: "tumblr",
    name: "Tumblr",
    category: "blog-cms",
    tagline: "Microblogging platform",
    description: "Tumblr is a microblogging platform with a reblog-driven community. Not built for serious SEO or content marketing but has a loyal niche audience.",
    pros: ["Community-driven", "Reblog mechanics", "Free hosting", "Good for visuals"],
    cons: ["Limited SEO", "Niche audience", "No custom CMS features", "Platform lock-in"],
    pricingSummary: "Free; Blog+ $3.99/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: true,
    bestFor: "visual creators and niche communities",
  },
  devto: {
    slug: "devto",
    name: "Dev.to",
    category: "blog-cms",
    tagline: "Developer community publishing",
    description: "Dev.to is a community-driven publishing platform for developers. Free to publish, built-in audience, but no custom domain or full ownership.",
    pros: ["Developer audience built-in", "Free to publish", "Open source (Forem)", "Great discoverability"],
    cons: ["No custom domain", "Content lives on their domain", "Limited SEO control", "Community norms"],
    pricingSummary: "Free",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: true,
    customDomain: false,
    bestFor: "developers seeking community exposure",
  },
  hugo: {
    slug: "hugo",
    name: "Hugo",
    category: "static-site-generator",
    tagline: "Lightning-fast static site generator",
    description: "Hugo is a Go-based static site generator — wildly fast builds but no admin UI. You write Markdown files and deploy. Great for tech blogs with developer authors only.",
    pros: ["Fastest builds", "Huge theme ecosystem", "Single binary", "Free + open source"],
    cons: ["No admin UI", "Markdown-only workflow", "Not for non-technical users", "No built-in SEO tools"],
    pricingSummary: "Free (host yourself)",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "developers who write in Markdown and git-deploy",
  },
  jekyll: {
    slug: "jekyll",
    name: "Jekyll",
    category: "static-site-generator",
    tagline: "Ruby-based static site generator",
    description: "Jekyll powers GitHub Pages. Git-based workflow with Markdown posts. Great for engineering blogs that live alongside code, but no admin UI for non-technical authors.",
    pros: ["GitHub Pages default", "Ruby/Liquid templating", "Git-based workflow", "Free"],
    cons: ["No admin UI", "Slow builds at scale", "Requires Ruby", "No built-in SEO"],
    pricingSummary: "Free",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "engineers using GitHub Pages",
  },
  astro: {
    slug: "astro",
    name: "Astro",
    category: "static-site-generator",
    tagline: "Modern static-first web framework",
    description: "Astro is a modern web framework shipping zero JS by default. Great for content sites — but it's a framework, not a CMS. You need a backing data source.",
    pros: ["Zero JS by default", "Modern DX", "Islands architecture", "Framework-agnostic"],
    cons: ["No built-in CMS", "Requires dev skills", "No admin UI", "Needs separate hosting"],
    pricingSummary: "Free (framework)",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "modern content sites with developer teams",
  },
  docusaurus: {
    slug: "docusaurus",
    name: "Docusaurus",
    category: "docs-platform",
    tagline: "Docs-first static site generator",
    description: "Docusaurus by Meta is optimized for documentation sites with blog support. Great for projects needing both docs and a blog, but overkill for blog-only use.",
    pros: ["Docs-first", "Versioning built-in", "React-based", "Algolia search"],
    cons: ["Overkill for blog-only", "Requires devs", "No admin UI", "Not blog-optimized"],
    pricingSummary: "Free",
    openSource: true,
    selfHosted: true,
    aiBuiltIn: false,
    headlessApi: false,
    customDomain: true,
    bestFor: "open-source projects needing docs + blog",
  },
  gitbook: {
    slug: "gitbook",
    name: "GitBook",
    category: "docs-platform",
    tagline: "Modern documentation platform",
    description: "GitBook is a polished docs platform with git-based sync and a clean UI. Great for product docs but not for public blogging or marketing content.",
    pros: ["Clean doc UI", "Git sync", "Team features", "AI search"],
    cons: ["Docs-only focus", "No blog features", "Closed source", "Pricing scales"],
    pricingSummary: "Free; Plus $8/mo; Pro $15/mo",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: true,
    headlessApi: true,
    customDomain: true,
    bestFor: "product teams publishing docs",
  },
  mintlify: {
    slug: "mintlify",
    name: "Mintlify",
    category: "docs-platform",
    tagline: "Beautiful docs for modern products",
    description: "Mintlify is a rising docs platform with a premium design system, git-based workflow, and AI search. Dev-tool focused, not a general blog platform.",
    pros: ["Beautiful defaults", "MDX support", "Git-based", "AI search"],
    cons: ["Docs-only", "Not for blogs", "Closed source", "Paid for teams"],
    pricingSummary: "Free hobby; $150+/mo teams",
    openSource: false,
    selfHosted: false,
    aiBuiltIn: true,
    headlessApi: false,
    customDomain: true,
    bestFor: "dev tool companies publishing docs",
  },
};

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS[slug];
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return Object.values(PRODUCTS).filter((p) => p.category === category);
}

export const ALL_PRODUCT_SLUGS = Object.keys(PRODUCTS);
